/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import System.EcoSystem;
import System.Hospital.Hospital;
import System.UserAccount.UserAccount;
import System.InRequest.InRequest;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author raunak
 */
public class OrderJPanel extends JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Hospital hospital;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public OrderJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, Hospital hospital) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business= business;
        this.hospital = hospital;
        //valueLabel.setText(enterprise.getName());
        for(InRequest inRequest :business.getWorkQueue().getWorkRequestList()){
            if(inRequest.getSender().getPassword().equals(userAccount.getPassword())&& inRequest.getSender().getUsername().equals(userAccount.getUsername())){
                userAccount.getWorkQueue().getWorkRequestList().add(inRequest);
            }
        }
        populateRequestTable();
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        model.setRowCount(0);
        for(InRequest s:business.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[3];
            row[0]=s.getMessage();
            row[1]=s.getSender();
            row[2]=s.getStatus();
            model.addRow(row);
        }
        DefaultTableModel model_1 = (DefaultTableModel) orderJTable.getModel();
        model_1.setRowCount(0);
        for(String s: hospital.getMenu()){
            Object[] row = new Object[2];
            row[0]=s;
            model_1.addRow(row);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        workRequestJTable = new JTable();
        requestTestJButton = new JButton();
        refreshTestJButton = new JButton();
        orderJButton = new JButton();
        jScrollPane2 = new JScrollPane();
        orderJTable = new JTable();
        backJButton =new JButton();


        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


        workRequestJTable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Receiver", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
        }
        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 58, 375, 96));

        orderJTable.setModel(new DefaultTableModel(
                new Object [][] {
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null}
                },
                new String [] {
                        "menu", "number"
                }
        ) {
            Class[] types = new Class [] {
                    String.class, Integer.class
            };
            boolean[] canEdit = new boolean [] {
                    false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderJTable);
        if (orderJTable.getColumnModel().getColumnCount() > 0) {
            orderJTable.getColumnModel().getColumn(0).setResizable(false);
            orderJTable.getColumnModel().getColumn(1).setResizable(false);
        }
        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 58, 375, 96));

        orderJButton.setText("make order");
        orderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderJButtonActionPerformed(evt);
            }
        });
        add(orderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 215, -1, -1));

        requestTestJButton.setText("Request Test");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton,new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 215, -1, -1));

        backJButton.setText("back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonnActionPerformed(evt);
            }
        });
        add(backJButton,new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 315, -1, -1));

        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 215, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this,"please select a request");
            return;
        }
        InRequest inRequest =userAccount.getWorkQueue().getWorkRequestList().get(selectedRow);
        RequestLabTestJPanel s= new RequestLabTestJPanel(userProcessContainer,userAccount, inRequest);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add(s);
        crdLyt.next(userProcessContainer);
        
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void  backJButtonnActionPerformed(java.awt.event.ActionEvent evt) {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerAreaJPanel dwjp = (CustomerAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }

    private void orderJButtonActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultTableModel model = (DefaultTableModel) orderJTable.getModel();
        for(int i = 0; i<model.getRowCount(); i++) {
            for (int j = 1; j < model.getColumnCount(); j++) {
                if (j == 1) {
                    Object temp = model.getValueAt(i, j);
                    int number;
                    if(temp==null){
                        number = 0;
                    }
                    else {
                        if (temp instanceof Number) {
                            number = (Integer) (temp);
                        } else {
                            JOptionPane.showMessageDialog(this, "wrong input");
                            return;
                        }
                    }
                }
            }
        }
        InRequest inRequest = new InRequest("",userAccount,null,"wait for accept", hospital,null);
        business.getWorkQueue().getWorkRequestList().add(inRequest);
        userAccount.getWorkQueue().getWorkRequestList().add(inRequest);
        JOptionPane.showMessageDialog(this,"oder made");
        populateRequestTable();
    }


    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();
        
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane jScrollPane1;
    private JButton refreshTestJButton;
    private JButton requestTestJButton;
    private JTable workRequestJTable;
    private JButton orderJButton;
    private JScrollPane jScrollPane2;
    private JTable orderJTable;
    private JButton backJButton;

    // End of variables declaration//GEN-END:variables
}
