/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PRCContactRole;

import System.BabyNurse.BabyNurse;
import System.CareCenterSystem;
import System.GODNurse.GODNurse;
import System.InRequest.InRequestList;
import System.PRC.PRC;
import System.PRCContact.PRCContact;
import System.PRC_GO.PRC_GO;
import System.PRC_PED.PRC_PED;
import System.UserAccount.UserAccount;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author raunak
 */
public class ManagePRCerJPanel extends JPanel {

    private JPanel userProcessContainer;
    private CareCenterSystem system;
    private UserAccount userAccount;
    private PRCContact prccontact;
    private PRC prc;
    private InRequestList inrequestList;
    private PRC_GO GOdocList;
    private PRC_PED PEDdocList;
    //private Pregnant pregnant;
    
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public ManagePRCerJPanel(JPanel userProcessContainer, UserAccount userAccount, CareCenterSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount=userAccount;
        this.prccontact = system.getPRCcontactDirectory().searchContact(userAccount.getUsername());
        this.system = system;
        this.prc=system.getPRCDirectory().searchPRC(prccontact.getPrc().getName());
        this.PEDdocList=prc.getPRC_PED();
        this.GOdocList=prc.getPRC_GO();
        this.inrequestList=prc.getInrequestDirectory();
        
        
        populateTable();
    }
    
    public void populateTable(){

        DefaultTableModel model2 = (DefaultTableModel) GOJTable.getModel();
        model2.setRowCount(0);
        for(GODNurse go:GOdocList.getGODNurseList()){
            Object[] row = new Object[5];
            row[0]=go;
            row[1]=go.getSex();
            row[2]=go.getUsrname();
            row[3]=go.getPassword();
            row[4]=go.getStatu();
            model2.addRow(row);
        }
        
        DefaultTableModel model3 = (DefaultTableModel) PEDJTable.getModel();
        model3.setRowCount(0);
        for(BabyNurse ped:PEDdocList.getBabyNurseList()){
            Object[] row = new Object[5];
            row[0]=ped;
            row[1]=ped.getSex();
            row[2]=ped.getUsrname();
            row[3]=ped.getPassword();
            row[4]=ped.getStatu();
            model2.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updatePED = new JButton();
        updateGO = new JButton();
        refreshJButton = new JButton();
        jScrollPane2 = new JScrollPane();
        GOJTable = new JTable();
        jScrollPane3 = new JScrollPane();
        PEDJTable = new JTable();
        Backbtn = new JButton();
        RemovePED = new JButton();
        addPED = new JButton();
        RemoveGO = new JButton();
        addGO = new JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updatePED.setText("Update Baby Nurse");
        updatePED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePEDActionPerformed(evt);
            }
        });
        add(updatePED, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 160, -1));

        updateGO.setText("Update GO Nurse");
        updateGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGOActionPerformed(evt);
            }
        });
        add(updateGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        GOJTable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "GO-Nurse", "Sex", "UserName", "Password", "Statu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(GOJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 670, 110));

        PEDJTable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Baby Nurse", "Sex", "UserName", "Password", "Statu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(PEDJTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 670, 110));

        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        RemovePED.setText("Remove");
        RemovePED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovePEDActionPerformed(evt);
            }
        });
        add(RemovePED, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        addPED.setText("Add Baby Nurse");
        addPED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPEDActionPerformed(evt);
            }
        });
        add(addPED, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        RemoveGO.setText("Remove");
        RemoveGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveGOActionPerformed(evt);
            }
        });
        add(RemoveGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        addGO.setText("Add GO Nurse");
        addGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGOActionPerformed(evt);
            }
        });
        add(addGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void updatePEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePEDActionPerformed

        int selectedRow=PEDJTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this,"please select a row");
            return;
        }
        BabyNurse ped=system.getBabyNurseDirectory().getDeliveryManArrayList().get(selectedRow);
        updateBabyNurseJPanel request=new updateBabyNurseJPanel(userProcessContainer,ped,system);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add(request);
        crdLyt.next(userProcessContainer);
        
        
    }//GEN-LAST:event_updatePEDActionPerformed

    private void updateGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGOActionPerformed
        int selectedRow=GOJTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this,"please select a row");
            return;
        }
        GODNurse go=system.getGodNurseDirectory().getDeliveryManArrayList().get(selectedRow);
        updatePRCDocJPanel request=new updatePRCDocJPanel(userProcessContainer,go,system);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add(request);
        crdLyt.next(userProcessContainer);

    }//GEN-LAST:event_updateGOActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagePRCerJPanel dwjp = (ManagePRCerJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackbtnActionPerformed

    private void addPEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPEDActionPerformed
        // TODO add your handling code here:
        addBabyNurseJPanel request=new addBabyNurseJPanel(userProcessContainer,system);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add(request);
        crdLyt.next(userProcessContainer);
    }//GEN-LAST:event_addPEDActionPerformed

    private void RemoveGOActionPerformed(ActionEvent evt) {//GEN-FIRST:event_RemoveGOActionPerformed
        // TODO add your handling code here:
        int selectedRow=GOJTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this,"please select a row");
            return;
        }
        
        system.getGodNurseDirectory().remove(system.getGodNurseDirectory().getDeliveryManArrayList().get(selectedRow).getUsrname());
        system.getUserAccountDirectory().remove(system.getUserAccountDirectory().searchUserAccount(system.getGodNurseDirectory().getDeliveryManArrayList().get(selectedRow).getUsrname()).getUsername());
        JOptionPane.showMessageDialog(this,"Successful");
        populateTable();
    }//GEN-LAST:event_RemoveGOActionPerformed

    private void RemovePEDActionPerformed(ActionEvent evt) {//GEN-FIRST:event_RemovePEDActionPerformed
        // TODO add your handling code here:
        int selectedRow=PEDJTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this,"please select a row");
            return;
        }
        
        system.getBabyNurseDirectory().remove(system.getBabyNurseDirectory().getDeliveryManArrayList().get(selectedRow).getUsrname());
        system.getUserAccountDirectory().remove(system.getUserAccountDirectory().searchUserAccount(system.getBabyNurseDirectory().getDeliveryManArrayList().get(selectedRow).getUsrname()).getUsername());
        JOptionPane.showMessageDialog(this,"Successful");
        populateTable();
    }//GEN-LAST:event_RemovePEDActionPerformed

    private void addGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGOActionPerformed
        // TODO add your handling code here:
        addPRCDocJPanel request=new addPRCDocJPanel(userProcessContainer,system);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add(request);
        crdLyt.next(userProcessContainer);
    }//GEN-LAST:event_addGOActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton Backbtn;
    private JTable GOJTable;
    private JTable PEDJTable;
    private JButton RemoveGO;
    private JButton RemovePED;
    private JButton addGO;
    private JButton addPED;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JButton refreshJButton;
    private JButton updateGO;
    private JButton updatePED;
    // End of variables declaration//GEN-END:variables
}
