/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PRCContactRole;

import System.CareCenterSystem;
import System.InRequest.InRequest;
import System.PRC.PRC;
import System.PRCContact.PRCContact;
import System.UserAccount.UserAccount;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author raunak
 */
public class PRCProcessOutJPanel extends JPanel {

    private JPanel userProcessContainer;
    private CareCenterSystem system;
    private UserAccount userAccount;
    private PRCContact prccontact;
    private PRC prc;
    private ArrayList<InRequest> inrequestList;
    
    //private Pregnant pregnant;
    
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public PRCProcessOutJPanel(JPanel userProcessContainer, UserAccount userAccount, CareCenterSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount=userAccount;
        this.prccontact = system.getPRCcontactDirectory().searchContact(userAccount.getUsername());
        this.system = system;
        this.prc=system.getPRCDirectory().searchPRC(prccontact.getPrc().getName());
        this.inrequestList=prc.getInrequestDirectory().getRequestList();
        
        
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model1 = (DefaultTableModel) RequestJTable.getModel();
        model1.setRowCount(0);
        for(InRequest s:inrequestList){
            if(s.getStatus().equals("Out")){
                Object[] row = new Object[3];
                row[0]=s;
                row[1]=s.getSender().getUsername();
                row[2]=s.getStatus();
                model1.addRow(row);
            }
                
            
        }

//        DefaultTableModel model2 = (DefaultTableModel) GOJTable.getModel();
//        model2.setRowCount(0);
//        for(GODoc go:GOdocList.getGODocList()){
//            Object[] row = new Object[2];
//            row[0]=go;
//            row[1]=go.getStatu();
//            model2.addRow(row);
//        }
//        
//        DefaultTableModel model3 = (DefaultTableModel) PEDJTable.getModel();
//        model3.setRowCount(0);
//        for(PEDoc ped:PEDdocList.getPEDocList()){
//            Object[] row = new Object[2];
//            row[0]=ped;
//            row[1]=ped.getStatu();
//            model3.addRow(row);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        RequestJTable = new JTable();
        refreshJButton = new JButton();
        jLabel3 = new JLabel();
        Backbtn = new JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RequestJTable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request ID", "Pregnant Name", "Statu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 670, 290));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 230, 20));

        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PRCProcessOutJPanel dwjp = (PRCProcessOutJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton Backbtn;
    private JTable RequestJTable;
    private JLabel jLabel3;
    private JScrollPane jScrollPane1;
    private JButton refreshJButton;
    // End of variables declaration//GEN-END:variables
}
