/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PRCContactRole;

import System.BabyNurse.BabyNurse;
import System.CareCenterSystem;

import javax.swing.*;
import java.awt.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author raunak
 */
public class updateBabyNurseJPanel extends JPanel {

    private JPanel userProcessContainer;
    private CareCenterSystem system;
    private BabyNurse babynurse;
    
    
    //private Pregnant pregnant;
    
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public updateBabyNurseJPanel(JPanel userProcessContainer, BabyNurse babynurse, CareCenterSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        //this.userAccount=userAccount;
        this.babynurse=babynurse;
        this.system = system;
        
        txtname.setText(babynurse.getName());
        txtsex.setText(babynurse.getSex());
        txtpsd.setText(babynurse.getPassword());
        txtstatu.setText(babynurse.getStatu());
        
        //populateTable();
    }
    
//    public void populateTable(){
//        DefaultTableModel model1 = (DefaultTableModel) RequestJTable.getModel();
//        model1.setRowCount(0);
//        for(InRequest s:inrequestList){
//            if(s.getStatus().equals("Out")){
//                Object[] row = new Object[3];
//                row[0]=s;
//                row[1]=s.getSender().getUsername();
//                row[2]=s.getStatus();
//                model1.addRow(row);
//            }
//                
//            
//        }
//
////        DefaultTableModel model2 = (DefaultTableModel) GOJTable.getModel();
////        model2.setRowCount(0);
////        for(GODoc go:GOdocList.getGODocList()){
////            Object[] row = new Object[2];
////            row[0]=go;
////            row[1]=go.getStatu();
////            model2.addRow(row);
////        }
////        
////        DefaultTableModel model3 = (DefaultTableModel) PEDJTable.getModel();
////        model3.setRowCount(0);
////        for(PEDoc ped:PEDdocList.getPEDocList()){
////            Object[] row = new Object[2];
////            row[0]=ped;
////            row[1]=ped.getStatu();
////            model3.addRow(row);
////        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backbtn = new JButton();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        txtstatu = new JTextField();
        txtname = new JTextField();
        txtsex = new JTextField();
        txtpsd = new JTextField();
        Submitbtn = new JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jLabel1.setText("Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel2.setText("Sex:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel4.setText("Password:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel5.setText("Statu:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));
        add(txtstatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 180, 30));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 180, 30));
        add(txtsex, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 180, 30));
        add(txtpsd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 180, 30));

        Submitbtn.setText("Submit");
        Submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbtnActionPerformed(evt);
            }
        });
        add(Submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagePRCerJPanel dwjp = (ManagePRCerJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackbtnActionPerformed

    private void SubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbtnActionPerformed
        // TODO add your handling code here:
        if(txtname.getText().equals("")||txtsex.getText().equals("")||txtpsd.getText().equals("")||txtstatu.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Have empty info!");
            return;
        }
        Pattern p=Pattern.compile(".*\\d+.*");
        Matcher m1=p.matcher(txtname.getText());
        Matcher m2=p.matcher(txtsex.getText());

        if(m1.matches()||m2.matches()){
            JOptionPane.showMessageDialog(this,"Invalid info!");
            return;
        }
        
        babynurse.setName(txtname.getText());
        babynurse.setSex(txtsex.getText());
        babynurse.setPassword(txtpsd.getText());
        babynurse.setStatu(txtstatu.getText());
        
        system.getUserAccountDirectory().searchUserAccount(babynurse.getUsrname()).setPassword(txtpsd.getText());
        
        JOptionPane.showMessageDialog(this,"Updated!");
        txtname.setText("");
        txtsex.setText("");
        txtpsd.setText("");
        txtstatu.setText("");
    }//GEN-LAST:event_SubmitbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton Backbtn;
    private JButton Submitbtn;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JTextField txtname;
    private JTextField txtpsd;
    private JTextField txtsex;
    private JTextField txtstatu;
    // End of variables declaration//GEN-END:variables
}
