/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import System.Baby.Baby;
import System.BabyInfo.BabyInfo;
import System.CareCenterSystem;
import System.UserAccount.UserAccount;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author HP
 */
public class BabyNurseJPanel extends JPanel {

    /**
     * Creates new form DoctorJPanel
     */

    JFileChooser fc;
    private JPanel userProcessContainer;
    private CareCenterSystem system;
    private UserAccount userAccount;
    //MimetypesFileTypeMap mtftp;



    public BabyNurseJPanel(JPanel userProcessContainer, UserAccount account, CareCenterSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system=system;
        this.userAccount = account;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDescri = new JLabel();
        jTextField1 = new JTextField();
        jScrollPane1 = new JScrollPane();
        tbDes = new JTable();
        btnSubmit = new JButton();
        jLabel1 = new JLabel();
        jTextField2 = new JTextField();

        lbDescri.setHorizontalAlignment(SwingConstants.RIGHT);
        lbDescri.setText("Description:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        tbDes.setModel(new DefaultTableModel(
                new Object [][] {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String [] {
                        "Check Date", "Pregnant Name", "Description"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDes);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel1.setText("Baby Name:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lbDescri)
                                                        .addComponent(jLabel1))
                                                .addGap(48, 48, 48)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(104, 104, 104)
                                                .addComponent(btnSubmit)))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 285, GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(139, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lbDescri)
                                                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                .addGap(33, 33, 33)
                                                .addComponent(btnSubmit))
                                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE))
                                .addGap(234, 234, 234))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals("")||jTextField2.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Have empty info!");
            return;
        }
        BabyInfo p = new BabyInfo();
        SimpleDateFormat sdf = new SimpleDateFormat();// 格式化时间
        sdf.applyPattern("yyyy-MM-dd HH:mm:ss a");// a为am/pm的标记
        Date date = new Date();// 获取当前时间
        if (system.getBabyDirectory().search(jTextField2.getText())==null){
            JOptionPane.showMessageDialog(this,"No such baby");
            return;
        }
        p.setCheckdate(sdf.format(date));
        p.setDescription(jTextField1.getText());
        p.setBirth(system.getBabyDirectory().search(jTextField2.getText()).getBirth());
        p.setMom(system.getBabyNurseDirectory().search(userAccount.getUsername()).getPregnant());
        p.setName(jTextField1.getText());
        p.setBaby(system.getBabyDirectory().search(jTextField2.getText()));
        system.getBabyDirectory().search(jTextField2.getText()).getBabyinfoDirectory().getBabyInfoArrayList().add(p);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tbDes.getModel();
        model.setRowCount(0);
        if (system.getBabyNurseDirectory().search(userAccount.getUsername()) == null || system.getBabyNurseDirectory().search(userAccount.getUsername()).getPregnant() == null || system.getBabyNurseDirectory().search(userAccount.getUsername()).getPregnant().getBabyArrayList() == null) {
            Object[] row = new Object[2];
            model.addRow(row);
        } else {
            for (Baby baby : system.getBabyNurseDirectory().search(userAccount.getUsername()).getPregnant().getBabyArrayList()) {
                {
                    for (BabyInfo babyInfo : baby.getBabyinfoDirectory().getBabyInfoArrayList()) {
                        if (babyInfo==null){
                            Object[] row = new Object[2];
                            model.addRow(row);
                            return;
                        }
                        Object[] row = new Object[2];
                        row[0] = babyInfo;
                        row[1] = babyInfo.getBaby().getName();
                        row[2] = babyInfo.getDescription();
                        model.addRow(row);
                    }
                }
            }
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnSubmit;
    private JLabel jLabel1;
    private JScrollPane jScrollPane1;
    private JTextField jTextField1;
    private JTextField jTextField2;
    private JLabel lbDescri;
    private JTable tbDes;
    // End of variables declaration//GEN-END:variables
}
