/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import System.CareCenterSystem;
import System.PregnantInfo.PregnantInfo;
import System.UserAccount.UserAccount;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author HP
 */
public class GONurseJPanel extends JPanel {

    /**
     * Creates new form DoctorJPanel
     */
    
    JFileChooser fc;
    private JPanel userProcessContainer;
    private CareCenterSystem system;
    private UserAccount userAccount;
    //MimetypesFileTypeMap mtftp;
    


    public GONurseJPanel(JPanel userProcessContainer, UserAccount account, CareCenterSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system=system;
        this.userAccount = account;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDescri = new JLabel();
        lbBUltraImage = new JLabel();
        btnupload = new JButton();
        jTextField1 = new JTextField();
        lbImage = new JLabel();
        jScrollPane1 = new JScrollPane();
        tbDes = new JTable();
        btnSubmit = new JButton();
        lbImage1 = new JLabel();
        txtImagePath = new JTextField();
        lbDescri1 = new JLabel();
        jButton1 = new JButton();
        jLabel1 = new JLabel();
        jTextField2 = new JTextField();

        lbDescri.setHorizontalAlignment(SwingConstants.RIGHT);
        lbDescri.setText("Description:");

        lbBUltraImage.setHorizontalAlignment(SwingConstants.RIGHT);
        lbBUltraImage.setText("B-Ultra Image:");

        btnupload.setText("UPLOAD");
        btnupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        lbImage.setText("Submit Image Area");

        tbDes.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Check Date", "Pregnant Name", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDes);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lbImage1.setText("Display Image Area");

        txtImagePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImagePathActionPerformed(evt);
            }
        });

        lbDescri1.setHorizontalAlignment(SwingConstants.RIGHT);
        lbDescri1.setText("Image Path:");

        jButton1.setText("Show image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pregnant Name:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSubmit)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDescri1)
                                .addGap(18, 18, 18)
                                .addComponent(txtImagePath, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbBUltraImage)
                                .addGap(18, 18, 18)
                                .addComponent(btnupload, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbDescri)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addComponent(lbImage, GroupLayout.PREFERRED_SIZE, 285, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(lbImage1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDescri))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(btnSubmit))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnupload)
                                    .addComponent(lbBUltraImage))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(txtImagePath, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDescri1))))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbImage, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(10, 10, 10)
                        .addComponent(lbImage1, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadActionPerformed

        int width=285, height=169;
        
        if(fc==null){
            fc=new JFileChooser();
        }
        fc.setCurrentDirectory(new java.io.File("/Users/zhuzixuan/NEU/INFO5100/images"));
        fc.setDialogTitle("Please choose an image");
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        
        if(fc.showOpenDialog(btnupload)==JFileChooser.APPROVE_OPTION){
            txtImagePath.setText(fc.getSelectedFile().getAbsolutePath());
            ImageIcon img=new ImageIcon(txtImagePath.getText());
            img.setImage(img.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
            lbImage.setIcon(img);
           
        }

            
        
    }//GEN-LAST:event_btnuploadActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||txtImagePath.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Have empty info!");
            return;
        }
        PregnantInfo p=new PregnantInfo();
        SimpleDateFormat sdf = new SimpleDateFormat();// 格式化时间
        sdf.applyPattern("yyyy-MM-dd HH:mm:ss a");// a为am/pm的标记
        Date date = new Date();// 获取当前时间
        p.setCheckdate(sdf.format(date));
        p.setDescription(jTextField1.getText());
        p.setImage(txtImagePath.getText());
        p.setPregnant(system.getPregnantDirectory().searchPregnant(jTextField2.getText()));
        system.getPregnantDirectory().searchPregnant(userAccount.getUsername()).getPregnantInfoArrayList().add(p);
        system.getPregnantInfoDirectory().createPregnanInfo(jTextField1.getText(),sdf.format(date), txtImagePath.getText(), system.getPregnantDirectory().searchPregnant(userAccount.getUsername()));
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtImagePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImagePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagePathActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tbDes.getSelectedRow()<0){
                JOptionPane.showMessageDialog(this,"Please select a row");
                return;
        }
        
        String date=(String)tbDes.getValueAt(tbDes.getSelectedRow(), 0);
        int width=285, height=169;
        //system.getPregnantDirectory().searchPregnant(name).getPregnantInfoArrayList()
        for(PregnantInfo i:system.getPregnantInfoDirectory().getPregnantInfoArrayList()){
            if(date.equals(i.getCheckdate())){
                ImageIcon img_=new ImageIcon(i.getImage());
                img_.setImage(img_.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
                lbImage1.setIcon(img_);
            }
            
        }
        

        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tbDes.getModel();
        model.setRowCount(0);
        if(system.getGODocDirectory().search(userAccount.getUsername())==null||system.getGODocDirectory().search(userAccount.getUsername()).getPregnant()==null||system.getGODocDirectory().search(userAccount.getUsername()).getPregnant().getPregnantInfoArrayList()==null){
            Object[] row = new Object[2];
            model.addRow(row);

        }
        else{
            for(PregnantInfo pregnantinfo:system.getGODocDirectory().search(userAccount.getUsername()).getPregnant().getPregnantInfoArrayList()){
                Object[] row = new Object[2];
                row[0]=pregnantinfo;
                row[1]=pregnantinfo.getPregnant().getUsername();
                row[2]=pregnantinfo.getDescription();
                model.addRow(row);

            }
        }

          
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnSubmit;
    private JButton btnupload;
    private JButton jButton1;
    private JLabel jLabel1;
    private JScrollPane jScrollPane1;
    private JTextField jTextField1;
    private JTextField jTextField2;
    private JLabel lbBUltraImage;
    private JLabel lbDescri;
    private JLabel lbDescri1;
    private JLabel lbImage;
    private JLabel lbImage1;
    private JTable tbDes;
    private JTextField txtImagePath;
    // End of variables declaration//GEN-END:variables
}
