/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import System.City.City;
import System.Community.Community;
import System.Hospital.Hospital;
import System.CareCenterSystem;
import System.PRC.PRC;
import System.Pregnant.Pregnant;
import System.Role.HospitalAdminRole;
import System.Role.PRCAdminRole;
import System.Role.Role;
import System.UserAccount.UserAccount;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author raunak
 */
public class CRUDJPanel extends JPanel {

    private JPanel userProcessContainer;
    private CareCenterSystem business;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public CRUDJPanel(JPanel userProcessContainer, CareCenterSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        model.setRowCount(0);
        for(Hospital s:business.getHospitalDirectory().getHospitalArrayList()){
            Object[] row = new Object[4];
            for(UserAccount v:business.getUserAccountDirectory().getUserAccountList()){
                if(s.getName().equals(v.getUsername())){
                    row[1]=v.getPassword();
                    row[2]=v.getRole().toString().substring(12);
                }
            }
            row[3] = s.getId();
            row[0]=s.getName();
            model.addRow(row);
        }
        for(PRC s:business.getPRCDirectory().getPRCtArrayList()){
            if(s==null){
                break;
            }
            Object[] row = new Object[4];
            for(UserAccount v:business.getUserAccountDirectory().getUserAccountList()){
                if(s.getName().equals(v.getUsername())){
                    row[1]=v.getPassword();
                    row[2]=v.getRole().toString().substring(12);
                }
            }
            row[3] = s.getId();
            row[0]=s.getName();
            model.addRow(row);
        }
        for(Pregnant s:business.getUserDirectory().getCustomerArrayList()){
            if(s==null){
                break;
            }
            Object[] row = new Object[4];
            for(UserAccount v:business.getUserAccountDirectory().getUserAccountList()){
                if(s.getUsername().equals(v.getUsername())){
                    row[1]=v.getPassword();
                    row[2]=v.getRole().toString().substring(12);
                }
            }
            row[0]=s.getName();
            row[3] = s.getId();
            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        workRequestJTable = new JTable();
        deleteJButton = new JButton();
        saveJButton = new JButton();
        refreshJButton = new JButton();
        passwordTextfield = new JTextField();
        usernameTextfield = new JTextField();
        addJButton =new JButton();
        passwordLabel = new JLabel();
        usernameLabel = new JLabel();
        backJButton = new JButton();
        roleLabel = new JLabel();
        roleComboBox = new JComboBox();
        cityLabel = new JLabel();
        cityTextfield = new JTextField();
        communityTextfield = new JTextField();
        communityLabel = new JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null,null,null},
                { null, null,null,null},
            },
            new String [] {
                "username","password","role","id"
            }
        ) {
            Class[] types = new Class [] {
                Object.class, String.class, String.class, String.class
            };
            boolean[] canEdit = new boolean [] {
                 true, true, false,false
            };


            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        roleLabel.setText("select a role");
        roleComboBox.addItem("hospital");
        roleComboBox.addItem("PRC");


        add(communityTextfield,new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 508, 375, 44));
        add(communityLabel,new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 508, 375, 44));
        communityLabel.setText("input community");
        add(cityLabel,new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 458, 375, 44));
        add(cityTextfield,new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 458, 375, 44));
        cityLabel.setText(("input city"));
        add(roleLabel,new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 408, 375, 44));
        add(roleComboBox,new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 408, 375, 44));
        usernameLabel.setText("username");
        add(usernameLabel,new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 308, 375, 44));
        add(usernameTextfield,new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 308, 375, 44));
        passwordLabel.setText("password");
        add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 358, 375, 44));
        add(passwordTextfield,new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 358, 375, 44));
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 58, 375, 96));

        deleteJButton.setText("delete");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });
        add(deleteJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 215, -1, -1));

        addJButton.setText("add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 555, -1, -1));

        saveJButton.setText("save changes");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(saveJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 215, -1, -1));


        backJButton.setText("back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 215, -1, -1));


        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 26, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if(usernameTextfield.getText().equals("")||passwordTextfield.getText().equals("")||communityTextfield.getText().equals("")||cityTextfield.getText().equals("")){
            JOptionPane.showMessageDialog(this,"empty input");
            return;
        }
        String userName = usernameTextfield.getText();
        if(!business.getUserAccountDirectory().checkIfUsernameIsUnique(userName)){
            JOptionPane.showMessageDialog(this,"username exist");
            usernameTextfield.setText("");
            return;
        }
        String communtiy = communityTextfield.getText();
        String combox = (String) roleComboBox.getSelectedItem();
        if (combox.equals("hospital")) {
            {
                business.getHospitalDirectory().createHospital(usernameTextfield.getText());
                Role role_2 = new HospitalAdminRole();
                String passWord = passwordTextfield.getText();
                Hospital hospital = new Hospital();
                hospital.setName(usernameTextfield.getText());
                boolean isadded=false;
                for (City s : business.getCityList().getCityArrayList()) {
                    if (s.getName().equals(cityTextfield.getText())) {
                        for (Community v : s.getCommunityArrayList()) {
                            if (v.getName().equals(communityTextfield.getText())){
                                v.getHospitalArrayList().add(hospital);
                            isadded = true;
                        }
                        }
                    }
                }
                if(!isadded){
                    JOptionPane.showMessageDialog(this,"wrong input of city or community");
                    usernameTextfield.setText("");
                    passwordTextfield.setText("");
                    cityTextfield.setText("");
                    communityTextfield.setText("");
                    return;
                }
                business.getUserAccountDirectory().createUserAccount(userName, passWord, role_2);

            }
        }
            else{
                PRC prc = new PRC();
                prc.setName(usernameTextfield.getText());
                business.getPRCDirectory().getPRCtArrayList().add(prc);
                Role role_2=new PRCAdminRole();
                String passWord = passwordTextfield.getText();
                business.getUserAccountDirectory().createUserAccount(userName,passWord,role_2);
                boolean isadded=false;
                for(City s : business.getCityList().getCityArrayList()) {
                    if (s.getName().equals(cityTextfield.getText())) {
                        for (Community v : s.getCommunityArrayList()) {
                            if (v.getName().equals(communityTextfield.getText())) {
                                v.getPrcArrayList().add(prc);
                                isadded = true;
                            }
                        }
                    }
                }
                if(!isadded) {
                    JOptionPane.showMessageDialog(this, "wrong input of city or community");
                    usernameTextfield.setText("");
                    passwordTextfield.setText("");
                    cityTextfield.setText("");
                    communityTextfield.setText("");
                    return;
                }


        }
        usernameTextfield.setText("");
        passwordTextfield.setText("");
        cityTextfield.setText("");
        communityTextfield.setText("");
        populateTable();
    }
    private void deleteJButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        int selectedRow = workRequestJTable.getSelectedRow();
        String username = (String) model.getValueAt(selectedRow,0);
        for(UserAccount s:business.getUserAccountDirectory().getUserAccountList()){
            if(s.getUsername().equals(username)){
                Role role = s.getRole();
                if(role.toString().indexOf("Hospital")!=-1)
                {
                    for(Hospital v:business.getHospitalDirectory().getHospitalArrayList()){
                        if(v.getName().equals(username)){
                            business.getHospitalDirectory().getHospitalArrayList().remove(v);
                        }
                    }
                }
                if(role.toString().indexOf("PRC")!=-1)
                {
                    for(PRC v:business.getPRCDirectory().getPRCList()){
                        if(v.getName().equals(username)){
                            business.getPRCDirectory().getPRCList().remove(v);
                        }
                    }
                }
                if(role.toString().indexOf("Preg")!=-1)
                {
                    for(Pregnant v:business.getUserDirectory().getCustomerArrayList()){
                        if(v.getName().equals(username)){
                            business.getUserDirectory().getCustomerArrayList().remove(v);
                        }
                    }
                }
                business.getUserAccountDirectory().getUserAccountList().remove(s);
            }
        }
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this,"please select a request");
            return;
        }
        JOptionPane.showMessageDialog(this,"deleted success");
        populateTable();
        
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt){
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel dwjp = (SystemAdminWorkAreaJPanel) component;
        dwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }


    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        for(int i = 0; i<model.getRowCount(); i++) {
                    String temp_name;
                    Object temp = model.getValueAt(i, 0);
                    if (temp instanceof Number) {
                        temp_name = Integer.toString((Integer) temp);
                    } else {
                        temp_name = (String) model.getValueAt(i, 0);
                    }
                    Role role;
                    String rolename = (String)model.getValueAt(i,2);
                    Object temp_1 = model.getValueAt(i, 1);
                    String password;
                    if (temp instanceof Number) {
                        int password_1 = (Integer) (temp);
                        password = Integer.toString(password_1);
                    } else {
                        password = (String) model.getValueAt(i, 1);
                    }
                    if(rolename.indexOf("Hospital")!=-1)
                    {
                        String originName = "";
                        for(Hospital v:business.getHospitalDirectory().getHospitalArrayList()){
                            if(v.getId()==(Integer)model.getValueAt(i,3)){
                                originName=v.getName();
                                v.setName(temp_name);
                            }
                        }
                        for(UserAccount v:business.getUserAccountDirectory().getUserAccountList()){
                            if(originName.equals(v.getUsername())){
                                v.setUsername(temp_name);
                                v.setPassword(password);
                            }
                        }
                        for(City v:business.getCityList().getCityArrayList()){
                            for(Community s:v.getCommunityArrayList()){
                                for(Hospital z:s.getHospitalArrayList()){
                                    if(originName.equals(z.getName())){
                                        z.setName(temp_name);
                                    }
                                }
                            }
                        }
                    }
                    if(rolename.indexOf("PRC")!=-1)
                    {
                        String originName = "";
                        for(PRC v:business.getPRCDirectory().getPRCList()){
                            if(v.getId()==(Integer)model.getValueAt(i,3)){
                                originName=v.getName();
                                v.setName(temp_name);
                            }
                        }
                        for(UserAccount v:business.getUserAccountDirectory().getUserAccountList()){
                            if(originName.equals(v.getUsername())){
                                v.setUsername(temp_name);
                                v.setPassword(password);
                            }
                        }
                        for(City v:business.getCityList().getCityArrayList()){
                            for(Community s:v.getCommunityArrayList()){
                                for(PRC z:s.getPrcArrayList()){
                                    if(originName.equals(z.getName())){
                                        z.setName(temp_name);
                                    }
                                }
                            }
                        }
                    }
                    if(rolename.indexOf("Preg")!=-1)
                    {
                        String originName = "";
                        for(Pregnant v:business.getUserDirectory().getCustomerArrayList()){
                            if(v.getId()==(Integer)model.getValueAt(i,3)){
                                originName=v.getName();
                                v.setName(temp_name);
                            }
                        }
                        for(UserAccount v:business.getUserAccountDirectory().getUserAccountList()){
                            if(originName.equals(v.getUsername())){
                                v.setUsername(temp_name);
                                v.setPassword(password);
                            }
                        }
                    }




        }
        JOptionPane.showMessageDialog(this,"changing success");
        populateTable();

    }//GEN-LAST:event_processJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton deleteJButton;
    private JScrollPane jScrollPane1;
    private JButton saveJButton;
    private JButton refreshJButton;
    private JTable workRequestJTable;
    private JTextField passwordTextfield;
    private JTextField usernameTextfield;
    private JButton addJButton;
    private JButton backJButton;
    private JLabel passwordLabel;
    private JLabel usernameLabel;
    private JLabel roleLabel;
    private JComboBox roleComboBox;
    private JLabel cityLabel;
    private JTextField cityTextfield;
    private JLabel communityLabel;
    private JTextField communityTextfield;
    // End of variables declaration//GEN-END:variables
}
