/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalContact;

import System.CareCenterSystem;
import System.GODoc.GODoc;
import System.Hospital.Hospital;
import System.Role.GODoctorRole;
import System.Role.Role;

import javax.swing.*;
import java.awt.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author raunak
 */
public class addGOJPanel extends JPanel {

    private JPanel userProcessContainer;
    private CareCenterSystem system;
    
    
    //private Pregnant pregnant;
    
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public addGOJPanel(JPanel userProcessContainer, CareCenterSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        //this.userAccount=userAccount;
        this.system = system;
        
        //populateTable();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backbtn = new JButton();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        txthospital = new JTextField();
        txtname = new JTextField();
        txtsex = new JTextField();
        txtpsd = new JTextField();
        Submitbtn = new JButton();
        jLabel3 = new JLabel();
        txtusername = new JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jLabel1.setText("Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel2.setText("Sex:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel4.setText("Password:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel5.setText("Hospital:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));
        add(txthospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 180, 30));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 180, 30));
        add(txtsex, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 180, 30));
        add(txtpsd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 180, 30));

        Submitbtn.setText("Submit");
        Submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbtnActionPerformed(evt);
            }
        });
        add(Submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jLabel3.setText("UserName:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));
        add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDoctorJPanel dwjp = (ManageDoctorJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackbtnActionPerformed

    private void SubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbtnActionPerformed
        // TODO add your handling code here:
        if(txtname.getText().equals("")||txtsex.getText().equals("")||txtpsd.getText().equals("")||txthospital.getText().equals("")||txtusername.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Have empty info!");
            return;
        }
        Pattern p=Pattern.compile(".*\\d+.*");
        Matcher m1=p.matcher(txtname.getText());
        Matcher m2=p.matcher(txtsex.getText());
        Matcher m3=p.matcher(txtusername.getText());
        if(m1.matches()||m2.matches()||m2.matches()){
            JOptionPane.showMessageDialog(this,"Invalid info!");
            return;
        }
        if(system.getHospitalDirectory().searchHospital(txthospital.getText())==null){
            JOptionPane.showMessageDialog(this,"Invalid hospital!");
            return;
        }
        Hospital hospital=system.getHospitalDirectory().searchHospital(txthospital.getText());
        GODoc go=system.getGODocDirectory().createDeliverMan(txtname.getText(), txtusername.getText(), txtsex.getText(), hospital);
        Role r=new GODoctorRole();
        system.getUserAccountDirectory().createUserAccount(txtusername.getText(), txtpsd.getText(),r);
        hospital.getHospital_GO().addGOD(go);
        JOptionPane.showMessageDialog(this,"added!");
        txtname.setText("");
        txtsex.setText("");
        txtpsd.setText("");
        txthospital.setText("");
    }//GEN-LAST:event_SubmitbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton Backbtn;
    private JButton Submitbtn;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JTextField txthospital;
    private JTextField txtname;
    private JTextField txtpsd;
    private JTextField txtsex;
    private JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
