/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PregnantRole;

import System.CareCenterSystem;
import System.Hospital.Hospital;
import System.UserAccount.UserAccount;
import System.InRequest.InRequest;
import System.PRC.PRC;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class RequestInPRCJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CareCenterSystem system;
    private UserAccount userAccount;
    private UserAccount receiver;
    private String PrePeriod;
    private String status;
    private Date requestDate;
    private Date resolveDate;
//    private Hospital hospital;
//    private PRC prc;
    //private InRequest inRequest;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestInPRCJPanel(JPanel userProcessContainer, CareCenterSystem system,UserAccount account) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system=system;
        this.userAccount = account;

        populateRequestTable();
//this.inRequest = inRequest;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Submit = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("PRC Request:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 250, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null}
                },
                new String [] {
                        "Name", "Community"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this,"please select a PRC");
            return;
        }
        for(InRequest s:system.getInRequestList().getRequestList()){
            if(s.getSender().getUsername().equals(userAccount.getUsername())&&
                    s.getPrc().getName().equals(system.getPRCDirectory().getPRCList().get(selectedRow).getName())){
                if(s.getStatus().equals("Processing")||s.getStatus().equals("In PRC")||s.getStatus().equals("Requesting")){
                    JOptionPane.showMessageDialog(this,"You have requested this PRC!");
                    return;
                }
            }
        }
        SimpleDateFormat sdf = new SimpleDateFormat();// 格式化时间
        sdf.applyPattern("yyyy-MM-dd HH:mm:ss a");// a为am/pm的标记
        Date date = new Date();// 获取当前时间
        //System.out.println("现在时间：" + sdf.format(date));

        system.getInRequestList().createRequest(userAccount, null, "Processing", sdf.format(date), null, null,
                system.getPRCDirectory().getPRCList().get(selectedRow));
//        InRequest requestin=userAccount.getPRCinRequestList().createRequest(userAccount, null, "Processing", sdf.format(date), null, null,
//                system.getPRCDirectory().getPRCtArrayList().get(selectedRow));
//
        system.getPRCDirectory().getPRCList().get(selectedRow);
        JOptionPane.showMessageDialog(this,"Processing!");


    }//GEN-LAST:event_SubmitActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PregnantMain dwjp = (PregnantMain) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for(PRC prc:system.getPRCDirectory().getPRCList()){
            Object[] row = new Object[2];
            row[0]=prc;
            row[1]=prc.getCommunity().name;
            model.addRow(row);
        }

    }
}
