/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PregnantRole;

import System.CareCenterSystem;
import System.City.City;
import System.InRequest.InRequest;
import System.UserAccount.UserAccount;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import userinterface.CityCommunity.CityJPanel;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author raunak
 */
public class RequestInfoJPanel extends JPanel {

    private JPanel userProcessContainer;
    private CareCenterSystem business;
    private UserAccount userAccount;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public RequestInfoJPanel(JPanel userProcessContainer, UserAccount userAccount, CareCenterSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business= business;
        populateRequestTable();
    }
    
    public void populateRequestTable(){
        DefaultTableModel model_1 = (DefaultTableModel) communityJTable.getModel();
        model_1.setRowCount(0);
        for(InRequest r:business.getInRequestList().getRequestList()){
            if(r.getSender().getUsername().equals(userAccount.getUsername())){
                if(r.getHospital()!=null){
                    Object[] row = new Object[4];
                    row[2]=r.getHospital().getName();
                    row[1]=r.getRequestDate();
                    row[3]=r.getStatus();
                    row[0]=r.getId();
                    model_1.addRow(row);
                }
                if(r.getPrc()!=null){
                    Object[] row = new Object[4];
                    row[2]=r.getPrc().getName();
                    row[1]=r.getRequestDate();
                    row[3]=r.getStatus();
                    row[0]=r.getId();
                    model_1.addRow(row);
                }

            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new JButton();
        jScrollPane2 = new JScrollPane();
        communityJTable = new JTable();
        refreshTestJButton = new JButton();
        deleteJButton = new JButton();
        communityJLabel = new JLabel();
        communityJTextfield = new JTextField();


        setLayout(new AbsoluteLayout());

        communityJTable.setModel(new DefaultTableModel(
                new Object [][] {
                        {null,null,null,null},
                        {null,null,null,null},
                        {null,null,null,null},
                        {null,null,null,null}
                },
                new String [] {
                        "id","request date","institution name","status"
                }
        ) {
            Class[] types = new Class [] {
                    Integer.class,String.class,String.class,String.class
            };
            boolean[] canEdit = new boolean [] {
                    false,false,false,false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(communityJTable);
        if (communityJTable.getColumnModel().getColumnCount() > 0) {
            communityJTable.getColumnModel().getColumn(0).setResizable(false);
            communityJTable.getColumnModel().getColumn(1).setResizable(false);
            communityJTable.getColumnModel().getColumn(2).setResizable(false);
            communityJTable.getColumnModel().getColumn(3).setResizable(false);
        }
        add(jScrollPane2, new AbsoluteConstraints(40, 58, 700, 96));

        add(communityJLabel,new AbsoluteConstraints(50, 315, -1, -1));
        add(communityJTextfield,new AbsoluteConstraints(150, 315, 375, 30));
        communityJLabel.setText("community name");
        deleteJButton.setText("save");
        deleteJButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });
        add(deleteJButton,new AbsoluteConstraints(50, 215, -1, -1));



        backJButton.setText("back");
        backJButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton,new AbsoluteConstraints(100, 215, -1, -1));

        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new AbsoluteConstraints(150, 215, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PregnantMain dwjp = (PregnantMain) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void refreshTestJButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();

    }//GEN-LAST:event_refreshTestJButtonActionPerformed


    private void deleteJButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel)communityJTable.getModel();
        int selectedRow = communityJTable.getSelectedRow();
        int id = (Integer) model.getValueAt(selectedRow,1);
        InRequest s = business.getInRequestList().searchById(id);
        business.getInRequestList().getRequestList().remove(s);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton backJButton;
    private JScrollPane jScrollPane2;
    private JTable communityJTable;
    private JButton refreshTestJButton;
    private JButton deleteJButton;
    private JTextField communityJTextfield;
    private JLabel communityJLabel;

    // End of variables declaration//GEN-END:variables
}
