/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PregnantRole;

import System.CareCenterSystem;
import System.Hospital.Hospital;
import System.Hospital.HospitalDirectory;
import System.UserAccount.UserAccount;
import System.InRequest.InRequest;
import System.PRC.PRC;

import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class RequestInHospitalJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CareCenterSystem system;
    private UserAccount userAccount;
    private ArrayList<Hospital> hospitalList;
    private String PrePeriod;
    private String status;
    private Date requestDate;
    private Date resolveDate;
//    private Hospital hospital;
//    private PRC prc;
    //private InRequest inRequest;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestInHospitalJPanel(JPanel userProcessContainer, CareCenterSystem system,UserAccount account) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system=system;
        this.userAccount = account;
        this.hospitalList=system.getHospitalDirectory().getHospitalArrayList();

        populateRequestTable();
//this.inRequest = inRequest;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Submit = new javax.swing.JButton();
        txt_PrePeriod = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));
        add(txt_PrePeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 140, 30));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Hospital Request:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 250, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null}
                },
                new String [] {
                        "Name", "Community"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 160));

        jLabel2.setText("Pregnant Period");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this,"please select a hospital");
            return;
        }
        if(txt_PrePeriod.getText().equals("")){
            JOptionPane.showMessageDialog(this,"please input your pregnant period");
            return;
        }
        for(InRequest s:system.getInRequestList().getRequestList()){
            if(s.getSender().getUsername().equals(userAccount.getUsername())&&
                    s.getHospital().getName().equals(system.getHospitalDirectory().getHospitalArrayList().get(selectedRow).getName())){
                if(s.getStatus().equals("Processing")||s.getStatus().equals("In hospital")||s.getStatus().equals("Requesting")){
                    JOptionPane.showMessageDialog(this,"You have requested this hospital!");
                    return;
                }
            }
        }
        SimpleDateFormat sdf = new SimpleDateFormat();// 格式化时间
        sdf.applyPattern("yyyy-MM-dd HH:mm:ss a");// a为am/pm的标记
        Date date = new Date();// 获取当前时间
        //System.out.println("现在时间：" + sdf.format(date));
        InRequest inRequest = system.getInRequestList().createRequest(userAccount, txt_PrePeriod.getText(), "Requesting",
                sdf.format(date),null,system.getHospitalDirectory().getHospitalArrayList().get(selectedRow),null);
//        InRequest requestin=userAccount.getHospitalinRequestListt().createRequest(userAccount,
//                txt_PrePeriod.getText(),"Requesting",
//                sdf.format(date),null,system.getHospitalDirectory().getHospitalArrayList().get(selectedRow),null);
        system.getHospitalDirectory().getHospitalArrayList().get(selectedRow).getInrequestDirectory().getRequestList().add(inRequest);
//
        txt_PrePeriod.setText("");
        JOptionPane.showMessageDialog(this,"Processing!");


    }//GEN-LAST:event_SubmitActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PregnantMain dwjp = (PregnantMain) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_PrePeriod;
    // End of variables declaration//GEN-END:variables

    private void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for(Hospital h:system.getHospitalDirectory().getHospitalArrayList()){
            Object[] row = new Object[3];
            row[0]=h;
            row[1]=h.getCommunity().name;

            model.addRow(row);
        }

    }
}
